config_files:
  language: zh_CN
database:
  use-mysql: false
  mysql:
    host: localhost
    port: 3306
    user: root
    password: root
    database: minecraft
settings:
  visible-distance: 20
  symbols:
    vanilla: "minecraft:"