config_files:
  language: zh_CN
database:
  use-mysql: false
  mysql:
    host: localhost
    port: 3306
    user: root
    password: root
    database: minecraft
settings:
  visible-distance: 8
  item-scale: 0.5
  block-scale: 0.25
  symbols:
    vanilla: "minecraft:"
